# Custom vars
version: 1.0.0

# Setup
title: Otto
description: >- # tagline can be a bit lengthy sometimes
  Otto theme is a simple Jekyll theme. It is an adaptation from Mark Otto's website.
url: https://kosalanuwan.github.io
baseurl: "/otto-theme"
repository: kosalanuwan/otto-theme
bugs: https://github.com/kosalanuwan/otto-theme/issues/new?assignees=&labels=&template=bug_report.md&title=
date_format: "%b %-d, %Y"
encoding: utf-8

show_post_meta: true
show_social_links: true

# Site author
author: 
  name: Kosala Nuwan Perera
  avatar: https://avatars1.githubusercontent.com/u/958227?s=460&u=9b166f138e17fd8a8a60177dbbaa79deff890ac6&v=4
  email: kosala.nuwan@gmail.com
  # Social
  github: kosalanuwan
  twitter: kosalanuwan
  linkedin: kosalanuwan
  blog: kosalanuwan

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  
  # _posts
  - scope: 
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Gems
plugins:
  - github-pages
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap   
  - jekyll-gist
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Optimize Jekyll
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config.docker.yml
  - '*.gemspec'
  - '*.gem'
  - '*.sh'
include:
  - _pages
  - .htaccess