# Custom vars
version: 1.2.0

# Setup
encoding: utf-8

url: https://kosalanuwan.github.io
baseurl: "/otto-theme"
repository: kosalanuwan/gh-site-otto-theme

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  
  # _posts
  - scope: 
      path: "_posts"
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Gems
plugins:
  - github-pages
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap   
  - jekyll-gist
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Optimize Jekyll
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - '.devcontainer'
  - '.vscode'
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - README.md
  - screenshot.png
  - robots.txt
  - vendor
  - ruby
  - '*.gemspec'
  - '*.gem'
include:
  - _pages
  - .htaccess