title_excerpt: "Oh, you are running on docker btw!"
url: http://localhost:8004
baseurl: ""
show_drafts: true
future: true
unpublished: true


# Collections
collections:
  preview:
    output: true
    permalink: /:collection/:path/
